services:
  identity: 
    build: 
      context: .
      dockerfile: src/Services/Identity/Api/Dockerfile 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./configs/identity.env
    ports:
      - 8081:8080
    secrets:
      - jwt_private_key
      - source: identity_connection_string
        target: ConnectionStrings__Postgres
    depends_on:
      - postgres
      - redis
  
  catalog:
    build: 
      context: .
      dockerfile: src/Services/Catalog/Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./configs/catalog.env
    ports:
      - 8082:8080
    secrets:
      - jwt_public_key
      - source: catalog_connection_string
        target: ConnectionStrings__Postgres
    depends_on:
      - postgres
      - redis
      - inventory
    
  inventory:
    build: 
      context: .
      dockerfile: src/Services/Inventory/Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./configs/inventory.env
    ports:
      - 8083:8080
    secrets:
      - jwt_public_key
      - source: inventory_connection_string
        target: ConnectionStrings__Postgres
    depends_on:
      - postgres
      - redis

  cart:
    build: 
      context: .
      dockerfile: src/Services/Cart/Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./configs/cart.env
    ports:
      - 8084:8080
    secrets:
      - jwt_public_key
      - source: cart_connection_string
        target: ConnectionStrings__Postgres
    depends_on:
      - postgres
      - redis
    
  postgres:
    image: postgres:18
    env_file:
      - ./configs/postgres.env
    volumes:  
      - pgdata:/var/lib/postgresql
    ports:
      - 5432:5432
    secrets:
      - postgres_password

  redis:
    image: redis:8
    ports:
      - 6379:6379

secrets:
  catalog_connection_string:
    file: ./secrets/catalog-connection-string.txt
  identity_connection_string:
    file: ./secrets/identity-connection-string.txt
  inventory_connection_string:
    file: ./secrets/inventory-connection-string.txt
  cart_connection_string:
    file: ./secrets/cart-connection-string.txt
  jwt_private_key: 
    file: ./secrets/jwt-private-key.pem
  jwt_public_key: 
    file: ./secrets/jwt-public-key.pem
  postgres_password: 
    file: ./secrets/postgres-password.txt

volumes:
  pgdata: