include:
  - path: composes/infra/postgres.yaml
    project_directory: .
  - path: composes/infra/rabbitmq.yaml
    project_directory: .
  - path: composes/infra/redis.yaml
    project_directory: .
  - path: composes/shared/secrets.yaml
    project_directory: .
  - path: composes/cart/api.yaml
    project_directory: .
  - path: composes/cart/worker.yaml
    project_directory: .
  - path: composes/catalog/api.yaml
    project_directory: .
  - path: composes/catalog/worker.yaml
    project_directory: .
  - path: composes/identity/api.yaml
    project_directory: .
  - path: composes/identity/worker.yaml
    project_directory: .
  - path: composes/inventory/api.yaml
    project_directory: .
  - path: composes/inventory/worker.yaml
    project_directory: .