include:
  - path: ./composes/compose.postgres.yaml
    project_directory: .
  - path: ./composes/compose.rabbitmq.yaml
    project_directory: .
  - path: ./composes/compose.redis.yaml
    project_directory: .
  - path: ./composes/compose.secrets.yaml
    project_directory: .
  - path: ./composes/compose.cart.api.yaml
    project_directory: .
  - path: ./composes/compose.cart.worker.yaml
    project_directory: .
  - path: ./composes/compose.catalog.api.yaml
    project_directory: .
  - path: ./composes/compose.identity.api.yaml
    project_directory: .
  - path: ./composes/compose.identity.worker.yaml
    project_directory: .
  - path: ./composes/compose.inventory.api.yaml
    project_directory: .