services:      
  inventory-api:
    build: 
      context: .
      dockerfile: src/Services/Inventory/Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - composes/inventory/environments/jwt.env
    ports:
      - 8083:8080
    secrets:
      - jwt_public_key
      - source: inventory_connection_string
        target: ConnectionStrings__Postgres
    depends_on:
      - postgres
      - redis

secrets:
  inventory_connection_string:
    file: composes/inventory/secrets/connection-string.txt
