global using MediatR;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Vendora.BuildingBlocks.Cqrs;
global using Vendora.BuildingBlocks.Messaging.Abstractions;
global using Vendora.BuildingBlocks.Results;
global using Vendora.Services.Cart.Application.Abstractions.Persistence;
global using Vendora.Services.Cart.Application.IntegrationEvents;
global using Vendora.Services.Cart.Domain.Carts;
