services:
  postgres:
    image: postgres:18
    env_file:
      - composes/infra/environments/postgres.env
    volumes:  
      - pgdata:/var/lib/postgresql
    ports:
      - 5432:5432
    secrets:
      - postgres_password

volumes:
  pgdata:

secrets:
  postgres_password: 
    file: composes/infra/secrets/postgres-password.txt